### ISSUE TITLE
[cetic/adminer] Helm 2 support

### ISSUE THREAD

**Issue by titan-epam** [cetic/helm-adminer#1]
In your description Steam support helm 2, but when I try to install applications I get this error due to the fact that I use helm 2 versions
helm install --name adminer --namespace=data  cetic/adminer
Error: apiVersion 'v2' is not valid. The value must be "v1"

**Comment by alexnuttinck** [comment]
Hello @titan-epam, yes I forget to update the requirements of the README.md. It is updated now.
You should use v0.1.2 of the chart if you want to use Helm v2 or I suggest you to upgrade your helm client.
