### ISSUE TITLE
Depricated apiVersion

### ISSUE THREAD

**Issue by imilic1** [cetic/helm-adminer#14]
https://github.com/cetic/helm-adminer/blob/5a67c868508b841de1625393ff102f17e2993dad/templates/ingress.yaml#L5

apiVersion: extensions/v1beta1 is depricated and can't be used in kuberentes 1.22+, need to use 
apiVersion: networking.k8s.io/v1 instead.

Please approve and merge this pull request which will fix the issue:

https://github.com/cetic/helm-adminer/pull/6

**Comment by banzo** [comment]
Fixed by #6
